_BASE_: '../../base/market1501_transreid.yml'

PEFT:
  METHOD: 'ssf'
  SSF:
    ENABLED: True
    BLOCKS: (6, 7, 8, 9, 10, 11)
    MERGE_ON_SAVE: False
    LR: 0.0
    FREEZE_BACKBONE: True
    OPTIMIZER_CASE: 1

OUTPUT_DIR: '../logs/market_vit_transreid_ssf_6_11_case1'
