_BASE_: '../base/market1501_transreid.yml'

PEFT:
  METHOD: 'lntune'
  LNTUNE:
    ENABLED: True
    BLOCKS: [4, 5, 6, 7, 8, 9, 10, 11]
    TRAIN_FINAL_NORM: True

OUTPUT_DIR: '../logs/market_vit_transreid_lntune_4_11'
