_BASE_: '../base/market1501_transreid.yml'

PEFT:
  METHOD: 'lora'
  LORA:
    R: 8
    ALPHA: 16
    DROPOUT: 0.05
    TARGETS: ["qkv", "proj", "fc1", "fc2"]
    TRAIN_HEAD: True
    MERGE_AT_EVAL: False
    BIAS: "none"
    SAVE_ADAPTER_ONLY: True
    BLOCKS: []

OUTPUT_DIR: '../logs/market_vit_transreid_lora_0_11_r8'
