_BASE_: '../base/market1501_transreid.yml'

PEFT:
  METHOD: 'ssf'
  SSF:
    ENABLED: True
    BLOCKS: ()
    MERGE_ON_SAVE: False
    LR: 0.0
    FREEZE_BACKBONE: True
    OPTIMIZER_CASE: 2

OUTPUT_DIR: '../logs/market_vit_transreid_ssf_0_11_case2'
