_BASE_: '../base/classification_transreid.yml'

PEFT:
  METHOD: 'ssf'
  SSF:
    BLOCKS: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  BASE_LR: 3.5e-4
  WEIGHT_DECAY: 1.0e-4
  WEIGHT_DECAY_BIAS: 1.0e-4
  BIAS_LR_FACTOR: 2

OUTPUT_DIR: '../logs/classification_ssf_0_11_case2'
