_BASE_: '../base/msmt17_transreid.yml'

PEFT:
  METHOD: 'lora'
  LORA:
    R: 16
    ALPHA: 32
    DROPOUT: 0.05
    TARGETS: ["qkv", "proj", "fc1", "fc2"]
    TRAIN_HEAD: True
    MERGE_AT_EVAL: False
    BIAS: "none"
    SAVE_ADAPTER_ONLY: True
    BLOCKS: [6, 7, 8, 9, 10, 11]

OUTPUT_DIR: '../logs/msmt17_lora_6_11_r16'
